//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenMachineLearningService.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feature
    {
        public string ScenarioId { get; set; }
        public string FeatureId { get; set; }
        public int Position { get; set; }
    
        public virtual Scenario Scenario { get; set; }
    }
}
