//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenMachineLearningService.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class InputSet
    {
        public string ScenarioId { get; set; }
        public string InputSetId { get; set; }
        public string Name { get; set; }
    
        public virtual Scenario Scenario { get; set; }
    }
}
