//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenMachineLearningService.Business
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OpenAIEntities : DbContext
    {
        public OpenAIEntities()
            : base("name=OpenAIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Input> Inputs { get; set; }
        public virtual DbSet<InputSet> InputSets { get; set; }
        public virtual DbSet<Scenario> Scenarios { get; set; }
    }
}
